//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DawsWebApiService.daws.svc.ny.gov {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core", ConfigurationName="daws.svc.ny.gov.dsmlSoap")]
    public interface dsmlSoap {
        
        // CODEGEN: Generating message contract since the operation directoryRequest is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="#batchRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DsmlMessage))]
        DawsWebApiService.daws.svc.ny.gov.directoryRequestResponse directoryRequest(DawsWebApiService.daws.svc.ny.gov.directoryRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="#batchRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<DawsWebApiService.daws.svc.ny.gov.directoryRequestResponse> directoryRequestAsync(DawsWebApiService.daws.svc.ny.gov.directoryRequestRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public partial class BatchRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AuthRequest authRequestField;
        
        private DsmlMessage[] itemsField;
        
        private string requestIDField;
        
        private BatchRequestProcessing processingField;
        
        private BatchRequestResponseOrder responseOrderField;
        
        private BatchRequestOnError onErrorField;
        
        public BatchRequest() {
            this.processingField = BatchRequestProcessing.sequential;
            this.responseOrderField = BatchRequestResponseOrder.sequential;
            this.onErrorField = BatchRequestOnError.exit;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AuthRequest authRequest {
            get {
                return this.authRequestField;
            }
            set {
                this.authRequestField = value;
                this.RaisePropertyChanged("authRequest");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("abandonRequest", typeof(AbandonRequest), Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("addRequest", typeof(AddRequest), Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("compareRequest", typeof(CompareRequest), Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("delRequest", typeof(DelRequest), Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("extendedRequest", typeof(ExtendedRequest), Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("modDNRequest", typeof(ModifyDNRequest), Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("modifyRequest", typeof(ModifyRequest), Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("searchRequest", typeof(SearchRequest), Order=1)]
        public DsmlMessage[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string requestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
                this.RaisePropertyChanged("requestID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(BatchRequestProcessing.sequential)]
        public BatchRequestProcessing processing {
            get {
                return this.processingField;
            }
            set {
                this.processingField = value;
                this.RaisePropertyChanged("processing");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(BatchRequestResponseOrder.sequential)]
        public BatchRequestResponseOrder responseOrder {
            get {
                return this.responseOrderField;
            }
            set {
                this.responseOrderField = value;
                this.RaisePropertyChanged("responseOrder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(BatchRequestOnError.exit)]
        public BatchRequestOnError onError {
            get {
                return this.onErrorField;
            }
            set {
                this.onErrorField = value;
                this.RaisePropertyChanged("onError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public partial class AuthRequest : DsmlMessage {
        
        private string principalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string principal {
            get {
                return this.principalField;
            }
            set {
                this.principalField = value;
                this.RaisePropertyChanged("principal");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExtendedRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbandonRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CompareRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ModifyDNRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DelRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AddRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ModifyRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SearchRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AuthRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LDAPResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExtendedResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SearchResultReference))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SearchResultEntry))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public partial class DsmlMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Control[] controlField;
        
        private string requestIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("control", Order=0)]
        public Control[] control {
            get {
                return this.controlField;
            }
            set {
                this.controlField = value;
                this.RaisePropertyChanged("control");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string requestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
                this.RaisePropertyChanged("requestID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public partial class Control : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object controlValueField;
        
        private string typeField;
        
        private bool criticalityField;
        
        public Control() {
            this.criticalityField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public object controlValue {
            get {
                return this.controlValueField;
            }
            set {
                this.controlValueField = value;
                this.RaisePropertyChanged("controlValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool criticality {
            get {
                return this.criticalityField;
            }
            set {
                this.criticalityField = value;
                this.RaisePropertyChanged("criticality");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public partial class DsmlModification : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] valueField;
        
        private string nameField;
        
        private DsmlModificationOperation operationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("value", Order=0)]
        public string[] value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DsmlModificationOperation operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
                this.RaisePropertyChanged("operation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public enum DsmlModificationOperation {
        
        /// <remarks/>
        add,
        
        /// <remarks/>
        delete,
        
        /// <remarks/>
        replace,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public partial class AttributeDescriptions : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AttributeDescription[] attributeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attribute", Order=0)]
        public AttributeDescription[] attribute {
            get {
                return this.attributeField;
            }
            set {
                this.attributeField = value;
                this.RaisePropertyChanged("attribute");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public partial class AttributeDescription : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public partial class MatchingRuleAssertion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string valueField;
        
        private bool dnAttributesField;
        
        private string matchingRuleField;
        
        private string nameField;
        
        public MatchingRuleAssertion() {
            this.dnAttributesField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool dnAttributes {
            get {
                return this.dnAttributesField;
            }
            set {
                this.dnAttributesField = value;
                this.RaisePropertyChanged("dnAttributes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string matchingRule {
            get {
                return this.matchingRuleField;
            }
            set {
                this.matchingRuleField = value;
                this.RaisePropertyChanged("matchingRule");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public partial class SubstringFilter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string initialField;
        
        private string[] anyField;
        
        private string finalField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string initial {
            get {
                return this.initialField;
            }
            set {
                this.initialField = value;
                this.RaisePropertyChanged("initial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("any", Order=1)]
        public string[] any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string final {
            get {
                return this.finalField;
            }
            set {
                this.finalField = value;
                this.RaisePropertyChanged("final");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public partial class AttributeValueAssertion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string valueField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public partial class FilterSet : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object[] itemsField;
        
        private ItemsChoiceType1[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("and", typeof(FilterSet), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("approxMatch", typeof(AttributeValueAssertion), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("equalityMatch", typeof(AttributeValueAssertion), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("extensibleMatch", typeof(MatchingRuleAssertion), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("greaterOrEqual", typeof(AttributeValueAssertion), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("lessOrEqual", typeof(AttributeValueAssertion), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("not", typeof(Filter), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("or", typeof(FilterSet), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("present", typeof(AttributeDescription), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("substrings", typeof(SubstringFilter), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType1[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
                this.RaisePropertyChanged("ItemsElementName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public partial class Filter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("and", typeof(FilterSet), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("approxMatch", typeof(AttributeValueAssertion), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("equalityMatch", typeof(AttributeValueAssertion), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("extensibleMatch", typeof(MatchingRuleAssertion), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("greaterOrEqual", typeof(AttributeValueAssertion), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("lessOrEqual", typeof(AttributeValueAssertion), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("not", typeof(Filter), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("or", typeof(FilterSet), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("present", typeof(AttributeDescription), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("substrings", typeof(SubstringFilter), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
                this.RaisePropertyChanged("ItemElementName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        and,
        
        /// <remarks/>
        approxMatch,
        
        /// <remarks/>
        equalityMatch,
        
        /// <remarks/>
        extensibleMatch,
        
        /// <remarks/>
        greaterOrEqual,
        
        /// <remarks/>
        lessOrEqual,
        
        /// <remarks/>
        not,
        
        /// <remarks/>
        or,
        
        /// <remarks/>
        present,
        
        /// <remarks/>
        substrings,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core", IncludeInSchema=false)]
    public enum ItemsChoiceType1 {
        
        /// <remarks/>
        and,
        
        /// <remarks/>
        approxMatch,
        
        /// <remarks/>
        equalityMatch,
        
        /// <remarks/>
        extensibleMatch,
        
        /// <remarks/>
        greaterOrEqual,
        
        /// <remarks/>
        lessOrEqual,
        
        /// <remarks/>
        not,
        
        /// <remarks/>
        or,
        
        /// <remarks/>
        present,
        
        /// <remarks/>
        substrings,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public partial class ErrorResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        private System.Xml.XmlElement detailField;
        
        private string requestIDField;
        
        private ErrorResponseType typeField;
        
        private bool typeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Xml.XmlElement detail {
            get {
                return this.detailField;
            }
            set {
                this.detailField = value;
                this.RaisePropertyChanged("detail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string requestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
                this.RaisePropertyChanged("requestID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ErrorResponseType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
                this.RaisePropertyChanged("typeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public enum ErrorResponseType {
        
        /// <remarks/>
        notAttempted,
        
        /// <remarks/>
        couldNotConnect,
        
        /// <remarks/>
        connectionClosed,
        
        /// <remarks/>
        malformedRequest,
        
        /// <remarks/>
        gatewayInternalError,
        
        /// <remarks/>
        authenticationFailed,
        
        /// <remarks/>
        unresolvableURI,
        
        /// <remarks/>
        other,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public partial class ResultCode : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private LDAPResultCode descrField;
        
        private bool descrFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public LDAPResultCode descr {
            get {
                return this.descrField;
            }
            set {
                this.descrField = value;
                this.RaisePropertyChanged("descr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool descrSpecified {
            get {
                return this.descrFieldSpecified;
            }
            set {
                this.descrFieldSpecified = value;
                this.RaisePropertyChanged("descrSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public enum LDAPResultCode {
        
        /// <remarks/>
        success,
        
        /// <remarks/>
        operationsError,
        
        /// <remarks/>
        protocolError,
        
        /// <remarks/>
        timeLimitExceeded,
        
        /// <remarks/>
        sizeLimitExceeded,
        
        /// <remarks/>
        compareFalse,
        
        /// <remarks/>
        compareTrue,
        
        /// <remarks/>
        authMethodNotSupported,
        
        /// <remarks/>
        strongAuthRequired,
        
        /// <remarks/>
        referral,
        
        /// <remarks/>
        adminLimitExceeded,
        
        /// <remarks/>
        unavailableCriticalExtension,
        
        /// <remarks/>
        confidentialityRequired,
        
        /// <remarks/>
        saslBindInProgress,
        
        /// <remarks/>
        noSuchAttribute,
        
        /// <remarks/>
        undefinedAttributeType,
        
        /// <remarks/>
        inappropriateMatching,
        
        /// <remarks/>
        constraintViolation,
        
        /// <remarks/>
        attributeOrValueExists,
        
        /// <remarks/>
        invalidAttributeSyntax,
        
        /// <remarks/>
        noSuchObject,
        
        /// <remarks/>
        aliasProblem,
        
        /// <remarks/>
        invalidDNSyntax,
        
        /// <remarks/>
        aliasDerefencingProblem,
        
        /// <remarks/>
        inappropriateAuthentication,
        
        /// <remarks/>
        invalidCredentials,
        
        /// <remarks/>
        insufficientAccessRights,
        
        /// <remarks/>
        busy,
        
        /// <remarks/>
        unavailable,
        
        /// <remarks/>
        unwillingToPerform,
        
        /// <remarks/>
        loopDetect,
        
        /// <remarks/>
        namingViolation,
        
        /// <remarks/>
        objectClassViolation,
        
        /// <remarks/>
        notAllowedOnNonLeaf,
        
        /// <remarks/>
        notAllowedOnRDN,
        
        /// <remarks/>
        entryAlreadyExists,
        
        /// <remarks/>
        objectClassModsProhibited,
        
        /// <remarks/>
        affectMultipleDSAs,
        
        /// <remarks/>
        other,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public partial class DsmlAttr : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] valueField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("value", Order=0)]
        public string[] value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public partial class SearchResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SearchResultEntry[] searchResultEntryField;
        
        private SearchResultReference[] searchResultReferenceField;
        
        private LDAPResult searchResultDoneField;
        
        private string requestIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("searchResultEntry", Order=0)]
        public SearchResultEntry[] searchResultEntry {
            get {
                return this.searchResultEntryField;
            }
            set {
                this.searchResultEntryField = value;
                this.RaisePropertyChanged("searchResultEntry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("searchResultReference", Order=1)]
        public SearchResultReference[] searchResultReference {
            get {
                return this.searchResultReferenceField;
            }
            set {
                this.searchResultReferenceField = value;
                this.RaisePropertyChanged("searchResultReference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public LDAPResult searchResultDone {
            get {
                return this.searchResultDoneField;
            }
            set {
                this.searchResultDoneField = value;
                this.RaisePropertyChanged("searchResultDone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string requestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
                this.RaisePropertyChanged("requestID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public partial class SearchResultEntry : DsmlMessage {
        
        private DsmlAttr[] attrField;
        
        private string dnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attr", Order=0)]
        public DsmlAttr[] attr {
            get {
                return this.attrField;
            }
            set {
                this.attrField = value;
                this.RaisePropertyChanged("attr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dn {
            get {
                return this.dnField;
            }
            set {
                this.dnField = value;
                this.RaisePropertyChanged("dn");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public partial class SearchResultReference : DsmlMessage {
        
        private string[] refField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ref", DataType="anyURI", Order=0)]
        public string[] @ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
                this.RaisePropertyChanged("ref");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExtendedResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public partial class LDAPResult : DsmlMessage {
        
        private ResultCode resultCodeField;
        
        private string errorMessageField;
        
        private string[] referralField;
        
        private string matchedDNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResultCode resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
                this.RaisePropertyChanged("resultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("referral", DataType="anyURI", Order=2)]
        public string[] referral {
            get {
                return this.referralField;
            }
            set {
                this.referralField = value;
                this.RaisePropertyChanged("referral");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string matchedDN {
            get {
                return this.matchedDNField;
            }
            set {
                this.matchedDNField = value;
                this.RaisePropertyChanged("matchedDN");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public partial class ExtendedResponse : LDAPResult {
        
        private string responseNameField;
        
        private object responseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string responseName {
            get {
                return this.responseNameField;
            }
            set {
                this.responseNameField = value;
                this.RaisePropertyChanged("responseName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public object response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
                this.RaisePropertyChanged("response");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public partial class BatchResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        private string requestIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("addResponse", typeof(LDAPResult), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("authResponse", typeof(LDAPResult), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("compareResponse", typeof(LDAPResult), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("delResponse", typeof(LDAPResult), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("errorResponse", typeof(ErrorResponse), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("extendedResponse", typeof(ExtendedResponse), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("modDNResponse", typeof(LDAPResult), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("modifyResponse", typeof(LDAPResult), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("searchResponse", typeof(SearchResponse), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
                this.RaisePropertyChanged("ItemsElementName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string requestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
                this.RaisePropertyChanged("requestID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        addResponse,
        
        /// <remarks/>
        authResponse,
        
        /// <remarks/>
        compareResponse,
        
        /// <remarks/>
        delResponse,
        
        /// <remarks/>
        errorResponse,
        
        /// <remarks/>
        extendedResponse,
        
        /// <remarks/>
        modDNResponse,
        
        /// <remarks/>
        modifyResponse,
        
        /// <remarks/>
        searchResponse,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public partial class ExtendedRequest : DsmlMessage {
        
        private string requestNameField;
        
        private object requestValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string requestName {
            get {
                return this.requestNameField;
            }
            set {
                this.requestNameField = value;
                this.RaisePropertyChanged("requestName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public object requestValue {
            get {
                return this.requestValueField;
            }
            set {
                this.requestValueField = value;
                this.RaisePropertyChanged("requestValue");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public partial class AbandonRequest : DsmlMessage {
        
        private string abandonIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string abandonID {
            get {
                return this.abandonIDField;
            }
            set {
                this.abandonIDField = value;
                this.RaisePropertyChanged("abandonID");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public partial class CompareRequest : DsmlMessage {
        
        private AttributeValueAssertion assertionField;
        
        private string dnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AttributeValueAssertion assertion {
            get {
                return this.assertionField;
            }
            set {
                this.assertionField = value;
                this.RaisePropertyChanged("assertion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dn {
            get {
                return this.dnField;
            }
            set {
                this.dnField = value;
                this.RaisePropertyChanged("dn");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public partial class ModifyDNRequest : DsmlMessage {
        
        private string dnField;
        
        private string newrdnField;
        
        private bool deleteoldrdnField;
        
        private string newSuperiorField;
        
        public ModifyDNRequest() {
            this.deleteoldrdnField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dn {
            get {
                return this.dnField;
            }
            set {
                this.dnField = value;
                this.RaisePropertyChanged("dn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string newrdn {
            get {
                return this.newrdnField;
            }
            set {
                this.newrdnField = value;
                this.RaisePropertyChanged("newrdn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool deleteoldrdn {
            get {
                return this.deleteoldrdnField;
            }
            set {
                this.deleteoldrdnField = value;
                this.RaisePropertyChanged("deleteoldrdn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string newSuperior {
            get {
                return this.newSuperiorField;
            }
            set {
                this.newSuperiorField = value;
                this.RaisePropertyChanged("newSuperior");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public partial class DelRequest : DsmlMessage {
        
        private string dnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dn {
            get {
                return this.dnField;
            }
            set {
                this.dnField = value;
                this.RaisePropertyChanged("dn");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public partial class AddRequest : DsmlMessage {
        
        private DsmlAttr[] attrField;
        
        private string dnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attr", Order=0)]
        public DsmlAttr[] attr {
            get {
                return this.attrField;
            }
            set {
                this.attrField = value;
                this.RaisePropertyChanged("attr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dn {
            get {
                return this.dnField;
            }
            set {
                this.dnField = value;
                this.RaisePropertyChanged("dn");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public partial class ModifyRequest : DsmlMessage {
        
        private DsmlModification[] modificationField;
        
        private string dnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("modification", Order=0)]
        public DsmlModification[] modification {
            get {
                return this.modificationField;
            }
            set {
                this.modificationField = value;
                this.RaisePropertyChanged("modification");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dn {
            get {
                return this.dnField;
            }
            set {
                this.dnField = value;
                this.RaisePropertyChanged("dn");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public partial class SearchRequest : DsmlMessage {
        
        private Filter filterField;
        
        private AttributeDescriptions attributesField;
        
        private string dnField;
        
        private SearchRequestScope scopeField;
        
        private SearchRequestDerefAliases derefAliasesField;
        
        private uint sizeLimitField;
        
        private uint timeLimitField;
        
        private bool typesOnlyField;
        
        public SearchRequest() {
            this.sizeLimitField = ((uint)(0));
            this.timeLimitField = ((uint)(0));
            this.typesOnlyField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Filter filter {
            get {
                return this.filterField;
            }
            set {
                this.filterField = value;
                this.RaisePropertyChanged("filter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public AttributeDescriptions attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
                this.RaisePropertyChanged("attributes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dn {
            get {
                return this.dnField;
            }
            set {
                this.dnField = value;
                this.RaisePropertyChanged("dn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SearchRequestScope scope {
            get {
                return this.scopeField;
            }
            set {
                this.scopeField = value;
                this.RaisePropertyChanged("scope");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SearchRequestDerefAliases derefAliases {
            get {
                return this.derefAliasesField;
            }
            set {
                this.derefAliasesField = value;
                this.RaisePropertyChanged("derefAliases");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(uint), "0")]
        public uint sizeLimit {
            get {
                return this.sizeLimitField;
            }
            set {
                this.sizeLimitField = value;
                this.RaisePropertyChanged("sizeLimit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(uint), "0")]
        public uint timeLimit {
            get {
                return this.timeLimitField;
            }
            set {
                this.timeLimitField = value;
                this.RaisePropertyChanged("timeLimit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool typesOnly {
            get {
                return this.typesOnlyField;
            }
            set {
                this.typesOnlyField = value;
                this.RaisePropertyChanged("typesOnly");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public enum SearchRequestScope {
        
        /// <remarks/>
        baseObject,
        
        /// <remarks/>
        singleLevel,
        
        /// <remarks/>
        wholeSubtree,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public enum SearchRequestDerefAliases {
        
        /// <remarks/>
        neverDerefAliases,
        
        /// <remarks/>
        derefInSearching,
        
        /// <remarks/>
        derefFindingBaseObj,
        
        /// <remarks/>
        derefAlways,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public enum BatchRequestProcessing {
        
        /// <remarks/>
        sequential,
        
        /// <remarks/>
        parallel,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public enum BatchRequestResponseOrder {
        
        /// <remarks/>
        sequential,
        
        /// <remarks/>
        unordered,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public enum BatchRequestOnError {
        
        /// <remarks/>
        resume,
        
        /// <remarks/>
        exit,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class directoryRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core", Order=0)]
        public DawsWebApiService.daws.svc.ny.gov.BatchRequest batchRequest;
        
        public directoryRequestRequest() {
        }
        
        public directoryRequestRequest(DawsWebApiService.daws.svc.ny.gov.BatchRequest batchRequest) {
            this.batchRequest = batchRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class directoryRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core", Order=0)]
        public DawsWebApiService.daws.svc.ny.gov.BatchResponse batchResponse;
        
        public directoryRequestResponse() {
        }
        
        public directoryRequestResponse(DawsWebApiService.daws.svc.ny.gov.BatchResponse batchResponse) {
            this.batchResponse = batchResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface dsmlSoapChannel : DawsWebApiService.daws.svc.ny.gov.dsmlSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class dsmlSoapClient : System.ServiceModel.ClientBase<DawsWebApiService.daws.svc.ny.gov.dsmlSoap>, DawsWebApiService.daws.svc.ny.gov.dsmlSoap {
        
        public dsmlSoapClient() {
        }
        
        public dsmlSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public dsmlSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public dsmlSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public dsmlSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DawsWebApiService.daws.svc.ny.gov.directoryRequestResponse DawsWebApiService.daws.svc.ny.gov.dsmlSoap.directoryRequest(DawsWebApiService.daws.svc.ny.gov.directoryRequestRequest request) {
            return base.Channel.directoryRequest(request);
        }
        
        public DawsWebApiService.daws.svc.ny.gov.BatchResponse directoryRequest(DawsWebApiService.daws.svc.ny.gov.BatchRequest batchRequest) {
            DawsWebApiService.daws.svc.ny.gov.directoryRequestRequest inValue = new DawsWebApiService.daws.svc.ny.gov.directoryRequestRequest();
            inValue.batchRequest = batchRequest;
            DawsWebApiService.daws.svc.ny.gov.directoryRequestResponse retVal = ((DawsWebApiService.daws.svc.ny.gov.dsmlSoap)(this)).directoryRequest(inValue);
            return retVal.batchResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DawsWebApiService.daws.svc.ny.gov.directoryRequestResponse> DawsWebApiService.daws.svc.ny.gov.dsmlSoap.directoryRequestAsync(DawsWebApiService.daws.svc.ny.gov.directoryRequestRequest request) {
            return base.Channel.directoryRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<DawsWebApiService.daws.svc.ny.gov.directoryRequestResponse> directoryRequestAsync(DawsWebApiService.daws.svc.ny.gov.BatchRequest batchRequest) {
            DawsWebApiService.daws.svc.ny.gov.directoryRequestRequest inValue = new DawsWebApiService.daws.svc.ny.gov.directoryRequestRequest();
            inValue.batchRequest = batchRequest;
            return ((DawsWebApiService.daws.svc.ny.gov.dsmlSoap)(this)).directoryRequestAsync(inValue);
        }
    }
}
